### ISSUE TITLE
Is it possible to add functionality?

### ISSUE THREAD

**Issue by shdudwns** [GalacticSoftware/GalacticGenisys#5]
Do you have many items in your motivation?Otherwise, I'd appreciate it if you could add it to me.And is server rek serious?Is the optimum?Can I add a multi-core function?

**Comment by caspervanneck** [comment]
Sorry @shdudwns  i dont know about multicore

**Comment by caspervanneck** [comment]
Rong buton

**Comment by shdudwns** [comment]
So, is it possible to add wigineung instead of multicore functions?Is the driver rek serious?
@caspervanneck
