### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shdudwns** [GalacticSoftware/GalacticGenisys#7]
Warning: require_once(/root/pm1/src/spl/ClassLoader.php): failed to open stream: No such file or directory in /root/pm1/src/pocketmine/PocketMine.php on line 106

Fatal error: require_once(): Failed opening required '/root/pm1/src/spl/ClassLoader.php' (include_path='.:') in /root/pm1/src/pocketmine/PocketMine.php on line 106
Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

**Comment by caspervanneck** [comment]
php fault
